import assert from 'node:assert/strict';
import { installFakeDom } from './fakedom.mjs';
installFakeDom();
const { parseCsv, renderCsv } = await import('../public/js/ui/csv.js');
let count = 0;
const check = (name, fn) => { fn(); count++; console.log('PASS '+name); };
check('quoted commas, escaped quotes, multiline and BOM/CRLF',()=>assert.deepEqual(parseCsv('\uFEFFid,note\r\n001,"A, B"\r\n002,"Say ""hi""\nand bye"\r\n').rows,[['id','note'],['001','A, B'],['002','Say "hi"\nand bye']]));
check('empty and trailing fields retained without phantom final row',()=>assert.deepEqual(parseCsv('a,b,\n,,').rows,[['a','b',''],['','','']]));
check('whitespace and number-like strings unchanged',()=>assert.deepEqual(parseCsv(' 01 ,1e3,=SUM(A1),false').rows,[[' 01 ','1e3','=SUM(A1)','false']]));
for(const s of ['a,"unfinished','a,b"c','"a"oops,b']) check('malformed quoting rejected '+s,()=>assert.ok(parseCsv(s).error));
check('empty BOM document clear state',()=>assert.ok(renderCsv('\uFEFF').textContent.includes('empty')));
check('error uses accessible message',()=>assert.ok(renderCsv('"unterminated').querySelector('[role=alert]')));
const item={name:'report.csv'}, view=renderCsv('id,note\n001,<img src=x onerror=alert(1)>\n002,"hello\nworld"',item);
check('safe text and leading zeros in semantic table',()=>{assert.equal(view.querySelector('td').textContent,'001');assert.equal(view.querySelector('img'),null);assert.ok(view.textContent.includes('<img'));assert.equal(view.querySelector('table').getAttribute('aria-label'),'report.csv');});
check('header toggle exposes first record and persists item choice',()=>{const toggle=view.querySelector('input');toggle.checked=false;toggle._fire('change');assert.equal(view.querySelector('td').textContent,'id');assert.equal(item.csvHeader,false);assert.equal(renderCsv('id\n001',item).querySelector('input').checked,false);});
check('uneven records keep extra data and explain padding',()=>{const v=renderCsv('a,b\nx,y,z\nq');assert.ok(v.textContent.includes('different field counts'));assert.equal(v.querySelectorAll('tbody td').length,6);assert.ok(v.textContent.includes('z'));});
check('many rows bounded and notice honest',()=>{const v=renderCsv('id\n'+Array.from({length:1000},(_,i)=>i).join('\n'));assert.equal(v.querySelectorAll('tbody tr').length,500);assert.ok(v.textContent.includes('remaining content is not shown or checked'));});
check('columns and total rendered cells bounded',()=>{const v=renderCsv(Array.from({length:600},()=>Array(80).fill('x').join(',')).join('\n'));assert.ok(v.querySelectorAll('tbody td').length<=10000);assert.equal(v.querySelectorAll('thead th').length,51);assert.ok(v.textContent.includes('Preview limited'));});
check('long cell clipped explicitly',()=>{const v=renderCsv('a\n'+ 'x'.repeat(5000));assert.equal(v.querySelector('td').textContent.length,2000);assert.ok(v.textContent.includes('shortened'));});
check('source cap never misreports incomplete quoted field as malformed',()=>{const p=parseCsv('a\n"'+'x'.repeat(1000001));assert.equal(p.limited,true);assert.equal(p.error,undefined);});
console.log(`${count}/${count} passed`);
