import assert from 'node:assert/strict';
import { mock } from 'node:test';
import { installFakeDom, installFakeWs } from './fakedom.mjs';
installFakeDom(); const ws = installFakeWs();
const { store } = await import('../public/js/store.js');
const { connectWs, send, pendingQueue } = await import('../public/js/ws.js');
const { initUpdates, updateControls } = await import('../public/js/ui/updates.js');
const { openSettings, closeSettings } = await import('../public/js/ui/settings.js');
const tick = () => new Promise(r=>setTimeout(r,10));
let n=0; const check=(label,fn)=>{fn();n++;console.log('PASS '+label);};
const state=(value,extra={})=>store.applyEvent({type:'engine.update',state:value,currentVersion:'2.3.1',latestVersion:'2.4.1',canInstall:true,...extra});
let socket; const FakeWS = globalThis.WebSocket; globalThis.WebSocket = class extends FakeWS { constructor(...args) { super(...args); socket = this; } };
initUpdates();connectWs();await tick();
state('available',{latestVersion:'2.4.0'});
check('available update offers explicit toast action',()=>assert.equal(document.querySelector('.toast-primary').textContent,'Update'));
const original=document.querySelector('#toast-engine-update');state('available',{latestVersion:'2.4.0'});
check('duplicate available snapshot does not nag',()=>assert.equal(document.querySelector('#toast-engine-update'),original));
// A normal toast expires after 3s; update notices must survive indefinitely.
mock.timers.enable({apis:['setTimeout']});
state('checking');mock.timers.tick(301);
check('automatic check removes stale install action',()=>assert.equal(document.querySelector('.toast-primary'),null));
state('available',{latestVersion:'2.4.0'});mock.timers.tick(30000);
check('same available version returns and survives ordinary timeout',()=>assert.equal(document.querySelector('.toast-primary').textContent,'Update'));
store.setConnected(false);mock.timers.tick(301);
check('disconnect removes stale install action',()=>assert.equal(document.querySelector('.toast-primary'),null));
store.setConnected(true);state('available',{latestVersion:'2.4.0'});mock.timers.tick(30000);
check('reconnect restores unacknowledged available notice',()=>assert.equal(document.querySelector('.toast-primary').textContent,'Update'));
const dismiss=document.querySelectorAll('.toast-act').find(b=>b.textContent==='Dismiss');dismiss._fire('click');mock.timers.tick(301);
state('checking');state('available',{latestVersion:'2.4.0'});store.setConnected(false);store.setConnected(true);state('available',{latestVersion:'2.4.0'});mock.timers.tick(30000);
check('explicit dismissal prevents same-version nag after check and reconnect',()=>assert.equal(document.querySelector('.toast-primary'),null));
state('available',{latestVersion:'2.4.1'});mock.timers.tick(0);
check('a new version still offers an update',()=>assert.equal(document.querySelector('.toast-primary').textContent,'Update'));
// Continue lifecycle checks with this version so duplicate snapshots match.
mock.timers.reset();
openSettings();
check('Settings persists version status and Update control',()=>assert.equal(document.querySelector('.set-update button').textContent,'Update'));
const installAction=document.querySelector('.toast-primary');
ws.clear();installAction._fire('click');
check('Update sends explicit install only and becomes busy',()=>{assert.equal(ws.sent.filter(m=>m.type==='engine.update.install').length,1);assert.equal(store.engineUpdate.state,'installing');assert.equal(document.querySelector('.set-update button').disabled,true);});
installAction._fire('click');
check('repeated action cannot install twice',()=>assert.equal(ws.sent.filter(m=>m.type==='engine.update.install').length,1));
const installing=document.querySelector('#toast-engine-update');state('installing');
check('duplicate installing snapshot keeps the same notice',()=>assert.equal(document.querySelector('#toast-engine-update'),installing));
state('error',{error:'Permission denied.'});
check('install failure visible in Settings and toast',()=>{assert.ok(document.querySelector('.set-update').textContent.includes('Permission denied'));assert.ok(document.querySelector('#toast-engine-update').textContent.includes('Permission denied'));});
const failed=document.querySelector('#toast-engine-update');state('error',{error:'Permission denied.'});
check('duplicate error preserves failure feedback',()=>assert.equal(document.querySelector('#toast-engine-update'),failed));
check('failed install offers a direct retry',()=>assert.equal(document.querySelector('.set-update button').textContent,'Retry update'));
ws.clear();document.querySelector('.set-update button')._fire('click');
check('retry uses same install control',()=>assert.equal(ws.last('engine.update.install').type,'engine.update.install'));
state('installed');
check('installed describes manual restart and sends none',()=>{assert.ok(document.querySelector('.set-update').textContent.includes('Restart CliDeck when ready'));assert.equal(ws.sent.some(m=>/restart/.test(m.type)),false);});
const installed=document.querySelector('#toast-engine-update');state('installed');
check('duplicate installed snapshot keeps the same notice',()=>assert.equal(document.querySelector('#toast-engine-update'),installed));
state('error',{error:'Installer failed after reconnect.'});
check('installation failure without local request offers retry notice',()=>assert.equal(document.querySelector('.toast-primary').textContent,'Retry update'));
state('available',{latestVersion:'2.5.0',canInstall:false,instruction:'Source checkout: update your checkout manually.'});
check('source checkout has Details toast and no install control',()=>{assert.equal(document.querySelector('.toast-primary').textContent,'Details');assert.equal(document.querySelector('.set-update button').textContent,'Check for updates');assert.ok(document.querySelector('.set-update').textContent.includes('Source checkout'));});
ws.clear();document.querySelector('.set-update button')._fire('click');
check('manual check sends check and disables while pending',()=>{assert.equal(ws.last('engine.update.check').type,'engine.update.check');assert.equal(document.querySelector('.set-update button').disabled,true);});
state('current');check('current status is clear',()=>assert.ok(updateControls().textContent.includes('up to date')));
state('error',{latestVersion:undefined,canInstall:false,error:'Registry unavailable.'});
await new Promise(r=>setTimeout(r,350));
check('automatic check failure stays quiet',()=>assert.equal(document.querySelector('#toast-engine-update'),null));
store.setConnected(false);ws.clear();document.querySelector('.set-update button')._fire('click');
check('offline controls do not send',()=>assert.equal(ws.sent.length,0));
socket.close();await tick();send({type:'engine.update.install'});send({type:'engine.update.check'});
check('update actions never enter offline queue',()=>assert.equal(pendingQueue().some(m=>m.type.startsWith('engine.update')),false));
closeSettings();console.log(`${n}/${n} passed`);process.exit(0);
